name: volsdf
channels:
  - pytorch
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- aadict=0.2.3
- asset=0.6.13
- blas=1.0
- blosc=1.21.0
- bottleneck=1.3.2
- brotli=1.0.9
- brunsli=0.1
- bzip2=1.0.8
- ca-certificates=2021.10.8
- cairo=1.16.0
- certifi=2021.10.8
- cfitsio=3.470
- charls=2.2.0
- cloudpickle=1.6.0
- colorama=0.4.4
- cudatoolkit=10.2.89
- cycler=0.11.0
- cytoolz=0.11.0
- dask-core=2.30.0
- dbus=1.13.6
- decorator=4.4.2
- expat=2.4.1
- ffmpeg=4.3.2
- fontconfig=2.13.1
- fonttools=4.25.0
- freetype=2.11.0
- gettext=0.19.8.1
- giflib=5.2.1
- glib=2.66.3
- globre=0.1.5
- gmp=6.2.1
- gnutls=3.6.15
- gputil=1.4.0
- graphite2=1.3.13
- gst-plugins-base=1.14.5
- gstreamer=1.14.5
- harfbuzz=2.4.0
- hdf5=1.10.6
- icu=64.2
- imagecodecs=2021.3.31
- imageio=2.9.0
- intel-openmp=2021.4.0
- jasper=1.900.1
- jbig=2.1
- jpeg=9d
- jxrlib=1.1
- kiwisolver=1.3.1
- krb5=1.18.2
- lame=3.100
- lcms2=2.12
- ld_impl_linux-64=2.35.1
- lerc=2.2.1
- libaec=1.0.4
- libblas=3.9.0
- libcblas=3.9.0
- libclang=9.0.1
- libcurl=7.71.1
- libdeflate=1.7
- libedit=3.1.20191231
- libffi=3.2.1
- libgcc-ng=9.3.0
- libgfortran-ng=7.5.0
- libgfortran4=7.5.0
- libglib=2.66.3
- libgomp=9.3.0
- libiconv=1.16
- libidn2=2.3.2
- liblapack=3.9.0
- liblapacke=3.9.0
- libllvm9=9.0.1
- libopencv=4.5.2
- libpng=1.6.37
- libprotobuf=3.16.0
- libssh2=1.9.0
- libstdcxx-ng=9.3.0
- libtasn1=4.16.0
- libtiff=4.3.0
- libunistring=0.9.10
- libuuid=2.32.1
- libuv=1.40.0
- libwebp=1.2.0
- libwebp-base=1.2.0
- libxcb=1.13
- libxkbcommon=0.10.0
- libxml2=2.9.10
- libzopfli=1.0.3
- lz4-c=1.9.3
- matplotlib-base=3.5.0
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- munkres=1.1.4
- ncurses=6.2
- nettle=3.7.3
- networkx=2.5
- nspr=4.30
- nss=3.67
- numexpr=2.7.3
- numpy=1.21.2
- numpy-base=1.21.2
- olefile=0.46
- opencv=4.5.2
- openh264=2.1.1
- openjpeg=2.4.0
- openssl=1.1.1l
- packaging=20.4
- pandas=1.3.4
- pcre=8.45
- pillow=8.4.0
- pip=21.2.4
- pixman=0.38.0
- plotly=5.4.0
- pthread-stubs=0.4
- py-opencv=4.5.2
- pyhocon=0.3.59
- pyparsing=3.0.6
- python=3.9.0
- python-dateutil=2.8.1
- python_abi=3.9
- pytorch=1.10.0
- pytorch-mutex=1.0
- pytz=2020.1
- pywavelets=1.1.1
- pyyaml=6.0
- qt=5.12.5
- readline=8.1
- scikit-image=0.18.3
- scipy=1.7.1
- setuptools=58.0.4
- six=1.16.0
- snappy=1.1.8
- sqlite=3.36.0
- tenacity=8.0.1
- tifffile=2020.10.1
- tk=8.6.11
- toolz=0.11.1
- torchaudio=0.10.0
- torchvision=0.11.1
- tqdm=4.62.3
- trimesh=3.9.36
- typing_extensions=3.10.0.2
- tzdata=2021e
- wheel=0.37.0
- x264=1!161.3030
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.5
- yaml=0.2.5
- zfp=0.5.5
- zlib=1.2.11
- zstd=1.5.0
